// ==========================================================================
// PostgreSQL Search Service — Implementation of SearchService interface
// ==========================================================================
// Uses PostgreSQL full-text search (tsvector/tsquery) with GIN indexes.
// Supports faceted filtering via the discovery_search RPC function.
// ==========================================================================

import type { SearchService, SearchQuery, SearchResults, SearchableEntity } from '../types';
import type { SupabaseClient } from '@supabase/supabase-js';

export class PostgresSearchService implements SearchService {
  constructor(private supabase: SupabaseClient) {}

  async index(entity: SearchableEntity): Promise<void> {
    // For supply_items, we upsert into the table
    // The search_vector is auto-generated by the GENERATED ALWAYS AS column
    const { error } = await this.supabase
      .from('supply_items')
      .upsert({
        id: entity.id,
        organization_id: entity.organizationId,
        title: entity.title,
        description: entity.description,
        type: entity.type as any,
        metadata: entity.metadata,
        status: 'active',
      }, { onConflict: 'id' });

    if (error) throw error;
  }

  async remove(id: string, _type: string): Promise<void> {
    const { error } = await this.supabase
      .from('supply_items')
      .update({ status: 'archived' })
      .eq('id', id);

    if (error) throw error;
  }

  async search(query: SearchQuery): Promise<SearchResults> {
    const { data, error } = await this.supabase.rpc('discovery_search', {
      p_search_text: query.text || null,
      p_types: query.types as any || null,
      p_sample_types: (query.filters?.sample_types as string[]) ?? null,
      p_disease_icd10: (query.filters?.disease as string) ?? null,
      p_country: (query.filters?.country as string) ?? null,
      p_commercial_only: (query.filters?.commercial_only === 'true') || null,
      p_limit: query.limit ?? 20,
      p_offset: query.offset ?? 0,
    });

    if (error) throw error;

    const results = data ?? [];
    const total = results.length > 0 ? Number(results[0].total_count) : 0;

    return {
      results: results.map((r: any) => ({
        id: r.id,
        type: r.type,
        title: r.title,
        excerpt: r.description?.slice(0, 200),
        score: r.search_rank,
        metadata: { organizationId: r.organization_id, disease: r.disease_label, country: r.country },
      })),
      total,
      limit: query.limit ?? 20,
      offset: query.offset ?? 0,
    };
  }

  async reindex(entities: SearchableEntity[]): Promise<void> {
    for (const entity of entities) {
      await this.index(entity);
    }
  }
}
