
f = open(r"C:\Users\jmend\Documents\ANTIGRAVITY FOLDER\kadarn-platform\.pi-subagents\artifacts\outputs\6eb85249\openspec\ktp-1.0-product-transformation-assessment.md", "a", encoding="utf-8")
f.write("## 6. What Should Be Deferred\n\n")
f.write("| Component | Reason | When to revisit |\n")
f.write("|-----------|--------|-----------------|\n")
f.write("| Marketplace monetization | No revenue model before readiness data | After 3+ programs live |\n")
f.write("| Sponsor portal expansion | Sponsors downstream now | After 3+ programs live |\n")
f.write("| Stripe / Payment gateway | No financial transactions in readiness phase | When Exchange activates |\n")
f.write("| Financial Engine (2 LOC stub) | No settlement needed | When Exchange activates |\n")
f.write("| External biobank integrations | Network adoption first | After 10+ institutions |\n")
f.write("| Full AI runtime (pgvector, ML) | Rule-based sufficient for readiness | When 50+ evaluations exist |\n")
f.write("| Complex workflow (Temporal SDK) | Readiness workflow simpler | When program execution |\n")
f.write("| Fulfillment Engine (stub) | No physical logistics during readiness | When programs execute |\n")
f.write("| Intelligence Engine (stub) | Analytics handles basic intelligence | When 100+ orgs |\n")
f.write("| Graph Query (stub) | Provenance graph handles lineage | When complex traversals needed |\n")
f.write("| Integration Engine (stub) | LIMS/CTMS not needed for readiness | When programs execute |\n")
f.close()
print('ok')
