// ==========================================================================
// HtmlRenderer — Published View → HTML artifact
// Sprint 9.4
// ==========================================================================

import type { ArtifactType } from '../value-objects/artifact-type.js';
import type { ArtifactRenderer, RenderedArtifact, ViewData } from './types.js';

/** Escape HTML entities to prevent XSS */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Render content as HTML-safe string */
function renderContent(content: string | Record<string, unknown>): string {
  if (typeof content === 'string') return escapeHtml(content);
  return escapeHtml(JSON.stringify(content, null, 2));
}

export class HtmlRenderer implements ArtifactRenderer {
  readonly artifactType: ArtifactType = 'html';

  render(view: ViewData): RenderedArtifact {
    const renderedAt = new Date().toISOString();

    const sectionsHtml = view.sections
      .sort((a, b) => a.order - b.order)
      .map(
        (s) =>
          `<article>\n    <h2>${escapeHtml(s.heading)}</h2>\n    <div>\n${renderContent(s.content)}\n    </div>\n  </article>`,
      )
      .join('\n');

    const data = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(view.title)}</title>
</head>
<body>
  <header>
    <h1>${escapeHtml(view.title)}</h1>
    <p><strong>Source:</strong> ${escapeHtml(view.source)}</p>
    <p><strong>Generated:</strong> ${escapeHtml(view.generatedAt)}</p>
  </header>
  <main>
  ${sectionsHtml}
  </main>
  <footer>
    <p>Rendered: ${escapeHtml(renderedAt)}</p>
    <p>Generated by Kadarn Delivery Engine</p>
  </footer>
</body>
</html>
`;

    return {
      contentType: 'text/html',
      data,
      artifactType: 'html',
      renderedAt,
      viewId: view.id,
      metadata: view.metadata,
    };
  }
}
