// ==========================================================================
// Kadarn Provenance — W3C PROV Type Definitions (PROV-DM / PROV-JSON)
// ==========================================================================
// KAA-003 §6 (Core Concepts), §8 (Semantic Mapping)
//
// These types model the W3C PROV data model for Kadarn provenance.
// They follow PROV-JSON conventions:
//   https://www.w3.org/TR/prov-jm/
//
// Key principle from KAA-003 §5:
//   "The existing provenance_nodes and provenance_edges tables are re-mapped
//    to PROV semantics without schema migration. The mapping is a semantic
//    layer, not a data move."
// ==========================================================================

// --------------------------------------------------------------------------
// PROV Identifiers
// --------------------------------------------------------------------------
// W3C PROV uses qualified names (prefix:localPart) as identifiers.
// In Kadarn, we use kadarn:<external_id> as the qualified identifier.
// --------------------------------------------------------------------------

export type ProvIdentifier = string; // e.g. "kadarn:specimen-001"

// --------------------------------------------------------------------------
// PROV Core Types
// --------------------------------------------------------------------------

/**
 * An entity is a physical, digital, conceptual, or other thing with some
 * fixed aspects. In Kadarn:
 *   - specimen, aliquot, consent, qc_result, dataset, document → Entity
 */
export interface ProvEntity {
  'prov:type'?: string;
  'kadarn:nodeType'?: string;
  'kadarn:label'?: string;
  'kadarn:externalId'?: string;
  'kadarn:organizationId'?: string;
  [key: string]: unknown;
}

/**
 * An activity is something that occurs over a period of time and acts
 * upon or with entities. In Kadarn:
 *   - processing_event, shipment, access_request, protocol, program → Activity
 */
export interface ProvActivity {
  'prov:type'?: string;
  'kadarn:nodeType'?: string;
  'kadarn:label'?: string;
  'kadarn:externalId'?: string;
  'kadarn:organizationId'?: string;
  'kadarn:startedAt'?: string;
  'kadarn:endedAt'?: string;
  [key: string]: unknown;
}

/**
 * An agent is something that bears some form of responsibility for an
 * activity, for the existence of an entity, or for another agent's activity.
 * In Kadarn:
 *   - organization → Agent
 *   - Future: user/profile → Person Agent
 */
export interface ProvAgent {
  'prov:type'?: string;
  'kadarn:nodeType'?: string;
  'kadarn:label'?: string;
  'kadarn:externalId'?: string;
  [key: string]: unknown;
}

// --------------------------------------------------------------------------
// PROV Relations
// --------------------------------------------------------------------------

/**
 * wasGeneratedBy: An entity was generated by an activity.
 *   e.g., aliquot wasGeneratedBy processing_event
 */
export interface ProvWasGeneratedBy {
  'prov:generatedEntity': ProvIdentifier;
  'prov:usedActivity': ProvIdentifier;
  'prov:time'?: string;
  [key: string]: unknown;
}

/**
 * used: An activity used an entity.
 *   e.g., processing_event used specimen
 */
export interface ProvUsed {
  'prov:usedActivity': ProvIdentifier;
  'prov:entity': ProvIdentifier;
  'prov:time'?: string;
  [key: string]: unknown;
}

/**
 * wasDerivedFrom: An entity was derived from another entity.
 *   e.g., dataset wasDerivedFrom aliquot
 *   e.g., correction wasDerivedFrom original (via derived_from edge)
 */
export interface ProvWasDerivedFrom {
  'prov:generatedEntity': ProvIdentifier;
  'prov:usedEntity': ProvIdentifier;
  'prov:activity'?: ProvIdentifier;
  'prov:generation'?: string;
  'prov:usage'?: string;
  [key: string]: unknown;
}

/**
 * wasAttributedTo: An entity was attributed to an agent.
 *   e.g., consent wasAttributedTo organization (donor)
 */
export interface ProvWasAttributedTo {
  'prov:entity': ProvIdentifier;
  'prov:agent': ProvIdentifier;
  [key: string]: unknown;
}

/**
 * wasAssociatedWith: An activity was associated with an agent.
 *   e.g., processing_event wasAssociatedWith organization (lab)
 */
export interface ProvWasAssociatedWith {
  'prov:activity': ProvIdentifier;
  'prov:agent': ProvIdentifier;
  'prov:plan'?: string;
  [key: string]: unknown;
}

/**
 * actedOnBehalfOf: An agent acted on behalf of another agent.
 *   e.g., CRO actedOnBehalfOf sponsor
 */
export interface ProvActedOnBehalfOf {
  'prov:agent': ProvIdentifier;
  'prov:responsible': ProvIdentifier;
  'prov:activity'?: ProvIdentifier;
  [key: string]: unknown;
}

/**
 * wasRevisionOf: An entity is a revision of another entity.
 *   Maps to Kadarn's derived_from edge with wasRevisionOf property.
 *   e.g., corrected_node wasRevisionOf original_node
 */
export interface ProvWasRevisionOf {
  'prov:newEntity': ProvIdentifier;
  'prov:oldEntity': ProvIdentifier;
  'prov:time'?: string;
  'kadarn:reason'?: string;
  [key: string]: unknown;
}

// --------------------------------------------------------------------------
// PROV Document
// --------------------------------------------------------------------------
//
// A PROV document is the complete provenance record, serializable as
// PROV-JSON. It contains all entities, activities, agents, and relations
// for a given provenance scope.
//
// Reference: https://www.w3.org/TR/prov-jm/#document-structure
// --------------------------------------------------------------------------

export interface ProvDocument {
  prefix: Record<string, string>;
  entity?: Record<ProvIdentifier, ProvEntity>;
  activity?: Record<ProvIdentifier, ProvActivity>;
  agent?: Record<ProvIdentifier, ProvAgent>;
  wasGeneratedBy?: Record<string, ProvWasGeneratedBy>;
  used?: Record<string, ProvUsed>;
  wasDerivedFrom?: Record<string, ProvWasDerivedFrom>;
  wasAttributedTo?: Record<string, ProvWasAttributedTo>;
  wasAssociatedWith?: Record<string, ProvWasAssociatedWith>;
  actedOnBehalfOf?: Record<string, ProvActedOnBehalfOf>;
  wasRevisionOf?: Record<string, ProvWasRevisionOf>;
}

// --------------------------------------------------------------------------
// Type helpers for mapping
// --------------------------------------------------------------------------

/**
 * Kadarn PROV category: which PROV type a Kadarn node_type maps to.
 */
export type ProvCategory = 'Entity' | 'Activity' | 'Agent';

/**
 * Mapping registry: node_type → PROV category and PROV type name.
 */
export interface NodeTypeMapping {
  category: ProvCategory;
  provType: string; // e.g. "kadarn:specimen" or "prov:Organization"
}

/**
 * Edge mapping: Kadarn edge_type + properties → PROV relation type.
 */
export type ProvRelationType =
  | 'wasGeneratedBy'
  | 'used'
  | 'wasDerivedFrom'
  | 'wasAttributedTo'
  | 'wasAssociatedWith'
  | 'actedOnBehalfOf'
  | 'wasRevisionOf';
