-- ============================================================================
-- KADARN v2 — Block 01-E: Evidence + Provenance v2
-- ============================================================================
-- Authority: Architecture Alignment Audit v2 §2.6, CANONICAL_MVP_SCOPE.md
-- Purpose: Evidence-to-source linkage, observations pipeline, evidence links,
--          and provenance_records_v2 table.
-- Migration: 091 (idempotent — all DDL guarded by IF NOT EXISTS / IF NOT FOUND)
-- Dependencies: 045 (evidence_nodes), 073 (evidence_sources), 074 (source_records)
-- ============================================================================

-- ############################################################################
-- PART 1: EPISTEMIC TYPE v2 ENUM
-- ############################################################################
-- KAD-LOOP-001: Canonical epistemic_type values for v2:
--   direct   — evidence directly observed/extracted from a source
--   derived  — evidence computed from other evidence via rules
--   inferred — evidence generated by AI/LLM inference
-- Coexists with migration 076 epistemic_type enum (observation/direct_claim/
-- derived_claim/inference). This v2 enum adds the column named
-- epistemic_type_v2 to avoid enum conflicts.

DO $$ BEGIN
    CREATE TYPE epistemic_type_v2 AS ENUM (
        'direct',
        'derived',
        'inferred'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ############################################################################
-- PART 2: OBSERVATION STATUS ENUM
-- ############################################################################

DO $$ BEGIN
    CREATE TYPE observation_status AS ENUM (
        'raw',
        'processed',
        'extracted',
        'superseded',
        'invalidated'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ############################################################################
-- PART 3: EVIDENCE LINK RELATIONSHIP TYPE ENUM
-- ############################################################################

DO $$ BEGIN
    CREATE TYPE evidence_link_relationship AS ENUM (
        'supports',
        'contradicts',
        'qualifies'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ############################################################################
-- PART 4: PROVENANCE ACTION ENUM (v2 canonical)
-- ############################################################################

DO $$ BEGIN
    CREATE TYPE provenance_action_v2 AS ENUM (
        'created',
        'updated',
        'deleted',
        'linked',
        'unlinked',
        'published',
        'reviewed',
        'approved',
        'rejected',
        'superseded'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ############################################################################
-- PART 5: ALTER evidence_nodes — ADD COLUMN source_id
-- ############################################################################
-- Bridges evidence to its originating evidence_source.
-- source_record_id already added in migrations 076/077 (idempotent ADD below).
-- epistemic_type_v2 supplements the 076 epistemic_type enum with v2 values.

ALTER TABLE IF EXISTS public.evidence_nodes
    ADD COLUMN IF NOT EXISTS source_id UUID
    REFERENCES public.evidence_sources(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.evidence_nodes
    ADD COLUMN IF NOT EXISTS source_record_id UUID
    REFERENCES public.source_records(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.evidence_nodes
    ADD COLUMN IF NOT EXISTS epistemic_type_v2 epistemic_type_v2;

-- Indexes for new columns
CREATE INDEX IF NOT EXISTS idx_evidence_nodes_source
    ON public.evidence_nodes(source_id);

CREATE INDEX IF NOT EXISTS idx_evidence_nodes_epistemic_v2
    ON public.evidence_nodes(epistemic_type_v2);

-- Comments
COMMENT ON COLUMN public.evidence_nodes.source_id IS
    'KADARN v2 Block 01-E — FK to evidence_sources. The originating logical source. NULL for legacy evidence.';
COMMENT ON COLUMN public.evidence_nodes.epistemic_type_v2 IS
    'KADARN v2 Block 01-E — Canonical epistemic type: direct (extracted/observed), derived (rule-computed), inferred (AI/LLM). Supplements migration 076 epistemic_type.';

-- ############################################################################
-- PART 6: TABLE — observations
-- ############################################################################
-- Sits between source_records (acquisition) and evidence_nodes (extraction).
-- An observation captures what was seen in a source record before it becomes
-- formal evidence. Observations are the raw unit of provenance.

CREATE TABLE IF NOT EXISTS public.observations (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_record_id    UUID NOT NULL
                        REFERENCES public.source_records(id) ON DELETE CASCADE,
    institution_id      UUID REFERENCES public.organizations(id) ON DELETE CASCADE,
    observed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    observed_by         UUID,                                    -- actor_id
    content             JSONB NOT NULL DEFAULT '{}',
    content_hash        TEXT,                                    -- SHA-256 of canonical content
    status              observation_status NOT NULL DEFAULT 'raw',
    locator_json        JSONB DEFAULT '{}',                     -- {page, section, span, uri}
    extraction_run_id   UUID,                                    -- FK to extraction_runs (optional, migration 090)
    metadata            JSONB DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_observations_sr ON public.observations(source_record_id);
CREATE INDEX IF NOT EXISTS idx_observations_status ON public.observations(status);
CREATE INDEX IF NOT EXISTS idx_observations_institution ON public.observations(institution_id);
CREATE INDEX IF NOT EXISTS idx_observations_observed ON public.observations(observed_at DESC);

-- Trigger: updated_at
DROP TRIGGER IF EXISTS trg_observations_updated_at ON public.observations;
CREATE TRIGGER trg_observations_updated_at
    BEFORE UPDATE ON public.observations
    FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();

COMMENT ON TABLE public.observations IS
    'KADARN v2 Block 01-E — Raw observations extracted from source records. Precursor to evidence_nodes.';
COMMENT ON COLUMN public.observations.content IS
    'JSONB: structured observation data including {type, value, confidence, raw_text}.';
COMMENT ON COLUMN public.observations.locator_json IS
    'JSONB: location within the source document — {page, section, span, uri}.';

-- ############################################################################
-- PART 7: TABLE — evidence_links
-- ############################################################################
-- Directed, typed links between evidence nodes.
-- Complements evidence_relationships (045) with a simpler relationship model:
--   supports    — evidence A makes evidence B more credible
--   contradicts — evidence A challenges evidence B
--   qualifies   — evidence A adds conditions/context to evidence B

CREATE TABLE IF NOT EXISTS public.evidence_links (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    evidence_node_id        UUID NOT NULL
                            REFERENCES public.evidence_nodes(id) ON DELETE CASCADE,
    target_evidence_node_id UUID NOT NULL
                            REFERENCES public.evidence_nodes(id) ON DELETE CASCADE,
    relationship_type       evidence_link_relationship NOT NULL,
    claim_id                UUID REFERENCES public.claims(id) ON DELETE SET NULL,
    rationale               TEXT,
    created_by              UUID,
    provenance              JSONB NOT NULL DEFAULT '{}',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT evidence_links_no_self_ref
        CHECK (evidence_node_id <> target_evidence_node_id),

    CONSTRAINT evidence_links_unique
        UNIQUE (evidence_node_id, target_evidence_node_id, relationship_type)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_evidence_links_node ON public.evidence_links(evidence_node_id);
CREATE INDEX IF NOT EXISTS idx_evidence_links_target ON public.evidence_links(target_evidence_node_id);
CREATE INDEX IF NOT EXISTS idx_evidence_links_relationship ON public.evidence_links(relationship_type);
CREATE INDEX IF NOT EXISTS idx_evidence_links_claim ON public.evidence_links(claim_id);

-- Trigger: updated_at
DROP TRIGGER IF EXISTS trg_evidence_links_updated_at ON public.evidence_links;
CREATE TRIGGER trg_evidence_links_updated_at
    BEFORE UPDATE ON public.evidence_links
    FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();

COMMENT ON TABLE public.evidence_links IS
    'KADARN v2 Block 01-E — Directed, typed links between evidence nodes. Supports/contradicts/qualifies semantics.';
COMMENT ON COLUMN public.evidence_links.relationship_type IS
    'supports: node A strengthens node B; contradicts: node A challenges node B; qualifies: node A adds conditions to node B.';

-- ############################################################################
-- PART 8: TABLE — provenance_records_v2
-- ############################################################################
-- Append-only provenance log for all KADARN entities.
-- Follows W3C PROV model: entity, activity, agent.
-- Each record captures: what changed (entity_type/entity_id), what action
-- occurred (action), who did it (actor_id), and the before/after state.

CREATE TABLE IF NOT EXISTS public.provenance_records_v2 (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type         TEXT NOT NULL,
    entity_id           UUID NOT NULL,
    action              provenance_action_v2 NOT NULL,
    actor_id            UUID,
    organization_id     UUID REFERENCES public.organizations(id) ON DELETE SET NULL,
    previous_state      JSONB,
    new_state           JSONB,
    correlation_id      UUID,
    causation_id        UUID,
    summary             TEXT,
    metadata            JSONB DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_provenance_v2_entity
    ON public.provenance_records_v2(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_provenance_v2_entity_id
    ON public.provenance_records_v2(entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_provenance_v2_action
    ON public.provenance_records_v2(action);
CREATE INDEX IF NOT EXISTS idx_provenance_v2_actor
    ON public.provenance_records_v2(actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_provenance_v2_org
    ON public.provenance_records_v2(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_provenance_v2_correlation
    ON public.provenance_records_v2(correlation_id, created_at DESC)
    WHERE correlation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_provenance_v2_created
    ON public.provenance_records_v2(created_at DESC);

-- Append-only enforcement
CREATE OR REPLACE FUNCTION provenance_records_v2_no_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'provenance_records_v2 is append-only. Record % cannot be modified.', OLD.id
        USING ERRCODE = 'restrict_violation';
END;
$$;

CREATE OR REPLACE FUNCTION provenance_records_v2_no_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'provenance_records_v2 is append-only. Record % cannot be deleted.', OLD.id
        USING ERRCODE = 'restrict_violation';
END;
$$;

DROP TRIGGER IF EXISTS trg_provenance_v2_no_update ON public.provenance_records_v2;
CREATE TRIGGER trg_provenance_v2_no_update
    BEFORE UPDATE ON public.provenance_records_v2
    FOR EACH ROW EXECUTE FUNCTION provenance_records_v2_no_update();

DROP TRIGGER IF EXISTS trg_provenance_v2_no_delete ON public.provenance_records_v2;
CREATE TRIGGER trg_provenance_v2_no_delete
    BEFORE DELETE ON public.provenance_records_v2
    FOR EACH ROW EXECUTE FUNCTION provenance_records_v2_no_delete();

COMMENT ON TABLE public.provenance_records_v2 IS
    'KADARN v2 Block 01-E — Append-only provenance log. W3C PROV-aligned: entity, activity (action), agent (actor).';
COMMENT ON COLUMN public.provenance_records_v2.entity_type IS
    'Entity type: evidence_node, claim, observation, source_record, evidence_source, etc.';
COMMENT ON COLUMN public.provenance_records_v2.correlation_id IS
    'Groups related provenance records (e.g., all records from one acquisition run).';
COMMENT ON COLUMN public.provenance_records_v2.causation_id IS
    'Points to the provenance record that caused this one (W3C wasInformedBy).';

-- ############################################################################
-- PART 9: ROW-LEVEL SECURITY
-- ############################################################################

ALTER TABLE public.observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provenance_records_v2 ENABLE ROW LEVEL SECURITY;

-- ------ observations RLS ------

CREATE POLICY obs_select_institution ON public.observations
    FOR SELECT
    USING (
        institution_id IS NULL
        OR institution_id IN (
            SELECT organization_id FROM public.organization_memberships
            WHERE user_id = auth.uid() AND status = 'active'
        )
        OR auth.role() = 'service_role'
    );

CREATE POLICY obs_insert_institution ON public.observations
    FOR INSERT
    WITH CHECK (
        institution_id IS NULL
        OR institution_id IN (
            SELECT organization_id FROM public.organization_memberships
            WHERE user_id = auth.uid() AND status = 'active'
        )
        OR auth.role() = 'service_role'
    );

CREATE POLICY obs_update_institution ON public.observations
    FOR UPDATE
    USING (
        institution_id IS NULL
        OR institution_id IN (
            SELECT organization_id FROM public.organization_memberships
            WHERE user_id = auth.uid() AND status = 'active'
        )
        OR auth.role() = 'service_role'
    );

CREATE POLICY obs_all_service ON public.observations
    FOR ALL
    USING (auth.role() = 'service_role');

-- ------ evidence_links RLS ------

CREATE POLICY el_select_org ON public.evidence_links
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.evidence_nodes en
            WHERE en.id = evidence_links.evidence_node_id
            AND (
                en.visibility->>'owningOrganizationId' IN (
                    SELECT organization_id::text FROM public.organization_memberships
                    WHERE user_id = auth.uid() AND status = 'active'
                )
                OR auth.role() = 'service_role'
            )
        )
    );

CREATE POLICY el_insert_org ON public.evidence_links
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.evidence_nodes en
            WHERE en.id = evidence_links.evidence_node_id
            AND en.visibility->>'owningOrganizationId' IN (
                SELECT organization_id::text FROM public.organization_memberships
                WHERE user_id = auth.uid() AND status = 'active'
            )
        )
        OR auth.role() = 'service_role'
    );

CREATE POLICY el_all_service ON public.evidence_links
    FOR ALL
    USING (auth.role() = 'service_role');

-- ------ provenance_records_v2 RLS ------

CREATE POLICY prv2_select_org ON public.provenance_records_v2
    FOR SELECT
    USING (
        organization_id IS NULL
        OR organization_id IN (
            SELECT organization_id FROM public.organization_memberships
            WHERE user_id = auth.uid() AND status = 'active'
        )
        OR auth.role() = 'service_role'
    );

CREATE POLICY prv2_insert_org ON public.provenance_records_v2
    FOR INSERT
    WITH CHECK (
        organization_id IS NULL
        OR organization_id IN (
            SELECT organization_id FROM public.organization_memberships
            WHERE user_id = auth.uid() AND status = 'active'
        )
        OR auth.role() = 'service_role'
    );

CREATE POLICY prv2_all_service ON public.provenance_records_v2
    FOR ALL
    USING (auth.role() = 'service_role');

-- ############################################################################
-- PART 10: GRANTS
-- ############################################################################

GRANT SELECT, INSERT, UPDATE ON public.observations TO authenticated, service_role;
GRANT DELETE ON public.observations TO service_role;

GRANT SELECT, INSERT, UPDATE ON public.evidence_links TO authenticated, service_role;
GRANT DELETE ON public.evidence_links TO service_role;

GRANT SELECT, INSERT ON public.provenance_records_v2 TO authenticated, service_role;
-- No UPDATE/DELETE on provenance_records_v2 (append-only, enforced by trigger)

-- ############################################################################
-- PART 11: COMMENTS
-- ############################################################################

COMMENT ON COLUMN public.observations.institution_id IS
    'NULL for global observations, set for institution-scoped ones.';
COMMENT ON COLUMN public.observations.extraction_run_id IS
    'FK to extraction_runs (migration 090) — tracks which extraction run produced this observation.';

COMMENT ON COLUMN public.evidence_links.claim_id IS
    'Optional FK to claims — scopes the link to a specific claim context.';
COMMENT ON COLUMN public.evidence_links.rationale IS
    'Human-readable explanation for why this link exists (e.g., "Both documents describe the same freezer model").';

COMMENT ON COLUMN public.provenance_records_v2.actor_id IS
    'The user or system agent that performed the action. NULL for automated/system actions.';
COMMENT ON COLUMN public.provenance_records_v2.summary IS
    'Human-readable summary of the provenance record (e.g., "Evidence node created from source record scan").';

-- ============================================================================
-- END OF MIGRATION 091
-- ============================================================================
